
[functions.github-token]
enabled = true
verify_jwt = false
import_map = "./functions/github-token/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/github-token/index.ts"

[functions.ai-assistant]
enabled = true
verify_jwt = true
import_map = "./functions/ai-assistant/deno.json"
entrypoint = "./functions/ai-assistant/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/github-token/*.html" ]

[functions.workplace-invite]
enabled = true
verify_jwt = true
import_map = "./functions/workplace-invite/deno.json"
entrypoint = "./functions/workplace-invite/index.ts"
